export const ConstantText = {
    GetDemo:"Get a Demo",
    Home:"Home",
    Industries:"Industries",
    Products:"Products",
    Blog:"Blog",
    ContactUs:"Contact Us",
    AboutUs:"About Us",
    BannerHeading:"Document Automation & Fraud Detection",
    AIPowered:"AI-Powered",
    bannerText:"Enhance security, accuracy, and efficiency with our cutting-edge AI solutions for seamless document processing and fraud prevention.",
    ExploreSolutions:"Explore Solutions",
    GrowthHeadingText:"AI-driven innovation for growth.",
    GrowthHeadingTitle:"Industries We Empower",
    Insurance:"Insurance",
    InsuranceText:"Automate claims processing with accurate document validation.",
    Lending:"Lending",
    LendingText:"Ensure faster loan approvals with fraud detection and instant verification.",
    Healthcare:"Healthcare",
    HealthcareText:"Streamline patient record management and ensure compliance with HIPAA standards.",
    featuresText:"features and benefits.",
    featuresTitle:"Our Products",
    LearnMore:"Learn More",
    ScheduleDemo:"Schedule a Demo",
    FeatureBadgeText1:"DocSim",
    FeatureBadgeText2:"DocPilot",
    FeatureBadgeText3:"Doxtract",
    FeatureTitle1:"AI-Powered Document Similarity Engine",
    FeatureTitle2:"Streamline Document Workflows with Automation",
    FeatureTitle3:"Extract, Validate, and Process Documents with Ease",
    FeatureSubTitle1:"Features:",
    FeatureSubTitle2:"Benefits:",
    BlogTitle:"Blogs",
    BlogText:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard.",
    ContentText:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's.",
    USOffice:"U.S. Office",
    USOfficeText1:"Aadrila Technologies INC,",
    USOfficeText2:"8 The Green, Ste R, in the City of Dover County of Kent Zip Code 19901.",
    IndiaOffice:"India Office",
    IndiaOfficeText1:"Aadrila Technologies Private Limited,",
    IndiaOfficeText2:"Unit 707, Lotus Trade Centre, Sahakar Nagar, New Link Road, Near D.N.Nagar, Andheri West, Mumbai, Maharashtra 400053.",


};